### ISSUE TITLE
Weights and biases go to NAN eventually

### ISSUE THREAD

**Issue by adammj** [fferroni/PhasedLSTM-Keras#13]
I've used a PLSTM layer in 3 different configurations on the same data, and after 50-200 epochs it will increasingly have more and more of the weights as NAN until all of them are, and the loss goes to zero.

The input data has no NANs, and has never produced a result like this with plain LSTM or GRU layers.

I suspect that the divisions for the time node are eventually failing, as they don't seem to have any method to prevent overflow.

**Comment by AndrasEros** [comment]
I have a similar issue with the only difference that it happens in the very beginning of the training. After a few batches in the first epoch the loss turns to NaN. I figured out that something was changed in Keras 2.0.6. I solved the issue by downgrading to Keras 2.0.5 and TF 1.2.0. I use SGD as optimizer. Optimizer settings are also important, lr=0.01 and momentum=0.2 worked for me. Try first reducing momentum and if that doesn't help reduce lr as well. I could not get it working with meaningful parameters on any release after Keras 2.0.5, only with momentum=0 and lr=0.0001.

**Comment by fferroni** [comment]
Ok, thanks for the information. I haven’t looked into the repo for a while, I’ll see if I have time to figure out what’s the issue.

Has anyone had an issue with Theano backend / CNTK backends? Because if it only appears in Tensorflow, you could simply wrap the Phased LSTM cell from tensorflow.contrib into a Keras later?

**Comment by AndrasEros** [comment]
I was struggling with this issue for a couple of weeks and I did try with Theano backend but only once and with one model. Behaviour was the same, loss turned to NaN after a few batches. According to the change log of Keras 2.0.6 the generator methods were improved including `fit_generator` and `evaluate_generator`. I suspect those changes have something to do with this issue. I also raised this issue because even my Keras standard BN LSTM network is impacted: https://github.com/fchollet/keras/issues/8430

**Comment by MyVanitar** [comment]
please update the repo

**Comment by AndrasEros** [comment]
@VanitarNordic Do you use bachnorm in the model when you get the NaN loss? What's your Keras and backend version?

**Comment by MyVanitar** [comment]
@AndrasEros 

No, I do not use batch normalization layer. I use Keras 2.1.2 and TensorFlow-1.4-CPU as the backend

**Comment by MyVanitar** [comment]
after few epoches it goes to the `-nan`, I set the model to stop at the iterations before `-nan`, but even it that case, I faced this error:

`ValueError: Unknown layer: PhasedLSTM`

it seems the problem is deep.

**Comment by AndrasEros** [comment]
It works for me now. I uninstalled an reinstalled everything from Nvidia, also Tensorflow 1.4 and Keras 2.1.2. Be sure that you use the right version of CuDNN, in my case I had 2 versions installed. I removed batch normalization layers and use only a single layer of PLSTM. I train with Adadelta. It all works fine.

**Comment by MyVanitar** [comment]
I also have a single layers of the PhasedLSTM, but I have it on CPU, I don't think CPU or GPU makes a difference.

**Comment by MyVanitar** [comment]
What is your python version?

**Comment by AndrasEros** [comment]
Well, on GPU I need all the Nvidia software so it makes a difference, actually makes it more complicated. CPU is always more simple. Versions:
conda 4.3.30
anaconda command line 1.5.1
python 3.5.2 (64 bit)

**Comment by MyVanitar** [comment]
My python version is 3.6.3. I'm not quite sure if that could cause this, But I don't think so :-(

Do you see any performance difference when using Phased LSTM?

**Comment by AndrasEros** [comment]
I thought tensorflow is not compatible with 3.6 but my information may be outdated. I do remember I did not upgrade in the past when 3.6 became available with Anaconda.
About performance: Yes, I have cyclical data and PLSTM performs much better than a 2 layered bach normalized LSTM.

**Comment by MyVanitar** [comment]
@AndrasEros 

1) Did you follow this example https://github.com/fferroni/PhasedLSTM-Keras/blob/master/examples/mnist_example.py to build your model?

2) According to the tensorflow repo, it support 3.5 and 3.6: https://github.com/tensorflow/tensorflow

**Comment by AndrasEros** [comment]
1. No, I built my model myself. I'm using the functional API.
2. You are right, both are supported. Some users however experience problems with Keras and 3.6.

Your problem seems to be an installation problem, a data problem or a too large model. If you want a confirmation on the first point I can try to run your model on my environment. I need your code and data if you want me to do that.
